"""trueskill rankings

Revision ID: 6b54e1ea9b39
Revises: bcc91bd31ad9
Create Date: 2020-05-14 21:54:02.744514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b54e1ea9b39'
down_revision = 'bcc91bd31ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trueskillrating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('matchtype', sa.String(length=64), nullable=True),
    sa.Column('mu', sa.DECIMAL(precision=2), nullable=True),
    sa.Column('sigma', sa.DECIMAL(precision=2), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=2), nullable=True),
    sa.Column('latest_delta', sa.DECIMAL(precision=2), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trueskillrating')
    # ### end Alembic commands ###
