"""new rating col for latest delta

Revision ID: a8f7ad03fa72
Revises: 2e654b91dcf2
Create Date: 2020-05-02 13:44:26.641051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f7ad03fa72'
down_revision = '2e654b91dcf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elorating', sa.Column('latest_delta', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elorating', 'latest_delta')
    # ### end Alembic commands ###
