"""trueskill rankings

Revision ID: acff47354f92
Revises: d413737c6bad
Create Date: 2020-05-23 12:37:21.462651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acff47354f92'
down_revision = 'd413737c6bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trueskillrating', sa.Column('latest_delta_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trueskillrating', 'latest_delta_date')
    # ### end Alembic commands ###
