"""trueskill rankings

Revision ID: bf7ab257ce86
Revises: acff47354f92
Create Date: 2020-09-21 20:20:10.970792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7ab257ce86'
down_revision = 'acff47354f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('quality', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'quality')
    # ### end Alembic commands ###
