"""new start

Revision ID: c2034667f8dc
Revises: a8f7ad03fa72
Create Date: 2020-05-08 18:47:14.002708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2034667f8dc'
down_revision = 'a8f7ad03fa72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'match', sa.Column('date', sa.Date(), nullable=True))
    op.drop_index('ix_match_timestamp', table_name='match')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column(u'match', 'timestamp')
    op.drop_column(u'match', 'results')
    op.drop_column(u'match', 'winner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'match', sa.Column('winner_id', sa.INTEGER(), nullable=True))
    op.add_column(u'match', sa.Column('results', sa.VARCHAR(length=1000), nullable=True))
    op.add_column(u'match', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_foreign_key(None, 'match', 'user', ['winner_id'], ['id'])
    op.create_index('ix_match_timestamp', 'match', ['timestamp'], unique=False)
    op.drop_column(u'match', 'date')
    op.drop_table('match_score')
    # ### end Alembic commands ###
